# Paths
features_dir: /scr/data/75ds_test/idr0017_mini/study_replication/images/dinov3_features # feature embedding path
metadata_path: "/mnt/cephfs/mir/jcaicedo/morphem/dataset/metadata/single-channel/v8/idr0017_meta.csv" # metadata csv path
save_dir: /scr/vidit/idr17_scores # directory to save analysis results

# Model and Benchmark Configuration
model_name: dinov3_features  #dinov2, subcell, openphenom_conc_masked
benchmark_test: recall_50 # auc_roc, replicate_corr, recall_k {Choose from 50 and 100}
fusion_type: early_fusion # late_fusion, early_fusion
mutations: ['HCT116 104-004', 'HCT116 104-007', 'HCT116 02-031', 'HCT116 02-006', 'HCT116 02-008', 'HCT116 104-008', 'HCT116 104-001', 'HCT116 02-030'] # Test is over 8 cell lines out of the 10!
distance_metric: euclidean # null or list of mutations as per metadata

# Distance Metrics
distance_metric: euclidean # euclidean, cosine
plot_graphs: false # true or false to save the graphs

# Workers
num_workers: 10 # number of parallel workers for processing
