[workspace]
authors = ["John <jgpeters3@wisc.edu>"]
channels = ["conda-forge"]
name = "simclr"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.8"

[tasks]

[dependencies]
python = "==3.10.16"

[pypi-dependencies]
torch = "==2.8.0"
torchmetrics = "==0.10.3"
torchvision = "==0.23.0"
pyyaml = ">=6.0.2, <7"
einops = ">=0.8.1, <0.9"
timm = ">=1.0.19, <2"
pandas = ">=2.3.2, <3"
diffusers = ">=0.35.1, <0.36"
