chammiv2:
  data_size: small # choices: {small, train}, Note "train" means "large" dataset
  ## which metadata to use for training, e.g., `multichannel`  means using `metadata_multi_channel_path`
  metadata_type: singlechannel  ## choices: {multichannel, singlechannel}
  metadata_path:  /projectnb/ivc-ml/morphem/chau_metadata/processed_{DATASIZE_PLACEHODER}/{METADATA_TYPE_PLACEHODER}_{DATASIZE_PLACEHODER}_full.csv
  ##### TODO: make `image_zip_path` automatic
  image_zip_path: /projectnb/ivc-ml/morphem/datasets/CHAMMI-75_{DATASIZE_PLACEHODER}.zip 
  sample_pair_path: /projectnb/ivc-ml/morphem/chau_metadata/processed_{DATASIZE_PLACEHODER}/cate_to_index_{DATASIZE_PLACEHODER}_{SPLIT_PLACEHODER}.json
  sample_pair: simclr ## choices: {simclr, supcon, ~}
  split: full  ## choices: {full, cate_atleast_100samples, cate_atleast_10samples}
  channel2id_path: /projectnb/ivc-ml/morphem/chau_metadata/processed_{DATASIZE_PLACEHODER}/channel2id_{DATASIZE_PLACEHODER}.json
  num_classes: FILL_LATER  ## not used for SSL
  in_chans: FILL_LATER # 1 of BoC, 25 for 
  image_size: [224, 224]
  use_guided_crops: True ## if True, use guided crops (from segmentation masks) for cropping cells
  guided_crops_path: /projectnb/ivc-ml/morphem/datasets/CHAMMI-75_guidance.zip
  normalization:
    mean: [0.083277255, 0.18028522, 0.027462168, 0.52211934, 0.43642986, 0.2067659, 0.14141469, 0.2232036, 0.09447627, 0.08861024, 0.18870227, 0.37047032, 0.6223977, 0.12366081, 0.5498078, 0.06756325, 0.086932845, 0.11684927, 0.13755327, 0.09684312, 0.47409117, 0.09954978, 0.11204452, 0.618473, 0.11519559, 0.083209276]
    std: [0.082984164, 0.12932123, 0.112391, 0.23920384, 0.17065245, 0.23178937, 0.12992783, 0.16092373, 0.14136083, 0.15021361, 0.23456252, 0.13649288, 0.15405382, 0.14766486, 0.25494263, 0.07862317, 0.08447149, 0.15076298, 0.14701504, 0.15048037, 0.13640004, 0.14274843, 0.14377056, 0.2915014, 0.13940126, 0.08181933]
    use_mean_std: false ## if False, each image is normalized  to [0-1]
  augmentation:
    train: simclr  ##  choices {~, CellAugmentation, simclr}. TODO: generalize this
    val: ~
  augment_on_gpu: False ## if True, do augmentations on GPU 