cache: /scr/jpeters/chammi_75_benchmarks/17cache
feature_extraction:
  crop: 100
  feature_agg: true
  model: channelvit
  model_mode: None
  model_path: /mnt/cephfs/mir/jcaicedo/projects/channel_vit_dinov1/models/0f6fa51_75ds_guarded/checkpoint.pth
  resize: 224
  resources:
    batch_size: 2048
    num_gpus: 3
    num_workers: 8
    threads: 16
  subcell_channel_map:
    er: null
    mt: null
    nucleus: 1
    protein: 2
metadata: /scr/data/75ds_test/idr0017_mini/metadata/idr0017_meta.csv
out_folder: /scr/data/75ds_test/idr0017_mini/study_replication
study: /scr/data/75ds_test/idr0017_mini/images
