cache: /scr/vidit/cache
feature_extraction:
  crop: 100
  feature_agg: true
  model: vit
  model_mode: None
  model_path: /scr/vidit/Foundation_Models/iclr_model_weights/DINO_IDRCELL
  resize: 224
  resources:
    batch_size: 2048
    num_gpus: 4
    num_workers: 8
    threads: 16
  subcell_channel_map:
    er: null
    mt: null
    nucleus: 1
    protein: 2
metadata: /scr/data/75ds_test/idr0017_mini/metadata/idr0017_meta.csv
out_folder: /scr/data/75ds_test/idr0017_mini/study_replication
study: /scr/data/75ds_test/idr0017_mini/images
