# Master Config file to change variables around
MODEL_TYPE: vit   # Model Types available - vit, mae, dinov2, dinov3, openphenom, subcell, chanvit_simclr in some cases
MODEL_PATH: /scr/vidit/DINO_CHAMMI-75_LARGE_DATASET/checkpoint.pth
MODEL_SIZE: small
NUM_GPUS: 8
MODEL_MODE: null

# CHAMMI Benchmark
CHAMMI: True  # Enable CHAMMI benchmark
CHAMMI_IMAGES_PATH: /scr/jpeters/c75_testing/datasets/CHAMMI
CHAMMI_FEATURES_PATH: /scr/jpeters/c75_testing/chammi/features
CHAMMI_SCORE_PATH: /scr/jpeters/c75_testing/chammi/scores
CHAMMI_BATCH_SIZE: 64

# HPA Benchmark
HPA: True  # Enable HPA benchmark
HPA_IMAGES_PATH: /scr/jpeters/c75_testing/datasets/mini-hpa
HPA_FEATURES_PATH: /scr/jpeters/c75_testing/hpa
HPA_BATCH_SIZE: 16
HPA_NUM_WORKERS: 8

#JUMP-CP Benchmark
JUMPCP: True  # Enable JUMP-CP1 benchmark
JUMPCP_IMAGES_PATH: /scr/data/CHAMMI-75/CHAMMI-75_test/Jump-CP
JUMPCP_FEATURES_PATH: /scr/jpeters/c75_testing/jump
JUMPCP_SCORE_PATH: /scr/jpeters/c75_testing/jump
JUMPCP_BATCH_SIZE: 16
JUMPCP_NUM_WORKERS: 8

#IDR-17 Benchmark
IDR-17: True # Enable/disable IDR-17 benchmark
# Paths and directories used for all rules
IDR_DATA_FOLDER: /scr/data/CHAMMI-75/CHAMMI-75_test/idr0017
IDR_FEATURES_PATH: /scr/jpeters/c75_testing/idr17
IDR_BENCHMARK_SAVE_DIR: /scr/jpeters/c75_testing/idr17
IDR_METADATA_PATH: /scr/jpeters/c75_testing/datasets/idr0017_mini/idr0017_meta.csv
IDR_NUM_WORKERS: 8

# Neuron Features Benchmark
CellPHIE: True  # Enable Neuron Features benchmark
CellPHIE_IMAGES_PATH: /scr/jpeters/c75_testing/datasets/neuron-features
CellPHIE_FEATURES_PATH: /scr/jpeters/c75_testing/neuron
CellPHIE_SCORE_PATH: /scr/jpeters/c75_testing/neuron
CellPHIE_EMBED_DIM: 384 # per channel embedding dimension size for CellPHIE
CellPHIE_BATCH_SIZE: 32
CellPHIE_NUM_WORKERS: 10

# RBC-MC Benchmark
RBC_MC: True  # Enable RBC-MC benchmark
RBC_MC_IMAGES_PATH: /scr/jpeters/c75_testing/datasets/rbc-mc
RBC_MC_FEATURES_PATH: /scr/jpeters/c75_testing/rbc
RBC_MC_SCORE_PATH: /scr/jpeters/c75_testing/rbc
RBC_MC_BATCH_SIZE: 32