# Master Config file to change variables around

MODEL_TYPE: vit   # Model Types available - vit, mae, dinov2, dinov3, openphenom, subcell in some cases
MODEL_PATH: /scr/vidit/Models/DINO_CHAMMI-75_LARGE
NUM_GPUS: 7

# CHAMMI Benchmark
CHAMMI: False  # Enable CHAMMI benchmark
CHAMMI_IMAGES_PATH: /scr/vidit/CHAMMI
CHAMMI_FEATURES_PATH: /scr/vidit/chammi_dino_features
CHAMMI_SCORE_PATH: /scr/vidit/CHAMMI_scores
CHAMMI_BATCH_SIZE: 16

# HPA Benchmark
HPA: False  # Enable HPA benchmark
HPA_IMAGES_PATH: /path/to/hpa/images
HPA_FEATURES_PATH: /path/to/hpa/Features
HPA_SCORE_PATH: /path/to/hpa/score
HPA_BATCH_SIZE: 16
HPA_NUM_WORKERS: 8

#JUMP-CP Benchmark




#IDR-17 Benchmark
IDR-17:True
# Paths and directories used for all rules
IDR_DATA_FOLDER: /scr/data/75ds_test/idr0017
cache: /scr/vidit/cache # location where it will temporarily unzip things



out_folder: /scr/data/75ds_test/idr0017/study_replication
cache: /scr/vidit/cache
study: /scr/data/75ds_test/idr0017/images
metadata: /scr/data/75ds_test/idr0017/metadata/idr0017_meta.csv
models: /mnt/cephfs/mir/jcaicedo/morphem/dataset/models

feature_extraction:
  # add in parameters needed for feature extraction
  run_job: true # set this to true to run feature extraction. False if you only want segmentations 
  feature_agg: true
  model_mode: None
  model_path: None
  model: dinov2 # openphenom, subcell, dinov2 
  subcell_channel_map: # to configure subcell mapping
    nucleus: 1 # Cannot be null
    protein: 2 # Cannot be null
    er: null # Can be null
    mt: null # Can be null
  crop: 100 
  resize: 224

  resources:
    num_gpus: 8 # Global when running locally and per job when running CHTC. Use 1 when running on CHTC in most cases.
    batch_size: 2048
    num_workers: 8
    threads: 16



# Neuron Features Benchmark
NEURON_FEATURES: False  # Enable Neuron Features benchmark
NEURON_IMAGES_PATH: /scr/vidit/neural_features/
NEURON_FEATURES_PATH: /scr/vidit/neural_features/neuron_feature_extraction
NEURON_SCORE_PATH: /scr/vidit/neural_features/neuron_feature_extraction
NEURON_BATCH_SIZE: 16
NEURON_NUM_WORKERS: 8
