# Master Config file to change variables around
MODEL_TYPE: vit   # Model Types available - vit, mae, dinov2, dinov3, openphenom, subcell, chanvit_simclr in some cases
MODEL_PATH: /scr/vidit/DINO_CHAMMI-75_LARGE_DATASET/checkpoint.pth
MODEL_SIZE: small
NUM_GPUS: 4
MODEL_MODE: null

# CHAMMI Benchmark
CHAMMI: False  # Enable CHAMMI benchmark
CHAMMI_IMAGES_PATH: /scr/vidit/Foundation_Models/CHAMMI
CHAMMI_FEATURES_PATH: /scr/vidit/chammi_features
CHAMMI_SCORE_PATH: /scr/vidit/CHAMMI_scores/DINO_BOC_75ds_small_changed_lr
CHAMMI_BATCH_SIZE: 64

# HPA Benchmark
HPA: False  # Enable HPA benchmark
HPA_IMAGES_PATH: /scr/data/75ds_test/mini-hpa
HPA_FEATURES_PATH: /scr/vidit/mini-hpa-scores/DINO-Features
HPA_BATCH_SIZE: 16
HPA_NUM_WORKERS: 8

#JUMP-CP Benchmark
JUMPCP: False  # Enable JUMP-CP1 benchmark
JUMPCP_IMAGES_PATH: /scr/data/75ds_test/jumpcp1compounds
JUMPCP_FEATURES_PATH: /scr/data/75ds_test/jumpcp1compounds
JUMPCP_SCORE_PATH: /scr/data/75ds_test/jumpcp1compounds
JUMPCP_BATCH_SIZE: 16
JUMPCP_NUM_WORKERS: 8

#IDR-17 Benchmark
IDR-17: False # Enable/disable IDR-17 benchmark
# Paths and directories used for all rules
IDR_DATA_FOLDER: /scr/data/idr0017
IDR_FEATURES_PATH: /scr/vidit/idr17_features/idrcell
IDR_NUM_WORKERS: 8

# Neuron Features Benchmark
NEURON_FEATURES: True  # Enable Neuron Features benchmark
NEURON_IMAGES_PATH: /scr/data/CHAMMI-75_test/CELLPHIE
NEURON_FEATURES_PATH: /scr/vidit/neural_features/DINO
NEURON_SCORE_PATH: /scr/vidit/neural_features/DINO
NEURON_BATCH_SIZE: 32
NEURON_NUM_WORKERS: 10
